### ISSUE TITLE
无法通过沿着新的路径运动

### ISSUE THREAD

**Issue by olmman** [hanruihua/neupan_ros#23]
你好，目前我在demo中将loop参数设置为false，并且在启动文件中将neupan_control节点参数中的refresh_initial_path设置为True。而后运行demo并通过rostopic pub向/initial_path话题发布新的路径信息，其内容大致如下：
```
# initial_path.yaml
header:
  seq: 0
  stamp: now
  frame_id: 'odom'
poses:
  - header:
      seq: 0
      stamp: now 
      frame_id: 'odom'
    pose:
      position: {x: 5.0, y: 0.0, z: 0.0}
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - header:
      seq: 0
      stamp: now 
      frame_id: 'odom'
    pose:
      position: {x: 3.0, y: 2.0, z: 0.0}
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
```
在RVIZ终端中查看时，发现触发了path_callback方法并打印了target path update，且RVIZ界面中也有新路径的可视化，但是小车却不沿着新路径运动，并且终端一直打印arrive at the target。后面我尝试在path_callback方法最后一行加入self.neupan_planner.reset()，但依然无法解决该问题。
现在应该如何修改，在loop:False时，/initial_path话题下的路径消息能够让小车沿着其路径运动。

此外，当loop:True时也存在一定的问题。在该情况下，向/initial_path话题发布相同的路径消息时小车虽然能够继续运动，但是运动路径与所发布的参考路径差别较大，尤其是参考路径拐点较多时，小车不会沿着参考路径而是会直接朝着终点移动，并且在到达终点后不会停止，而是继续朝前移动一段距离并在一个区域来回打转，同时终端持续打印loop, reset the path，这很明显与期望不符。

请问目前这两个问题应该怎样解决？
