### ISSUE TITLE
路径走s形

### ISSUE THREAD

**Issue by 2873468182** [hanruihua/neupan_ros#26]
您好， 我想问请问一下，我用gazebo仿真neupan规划的轨迹存在s形的情况，但是用ir-sim仿真就不会出出现这个问题，请问我需要从哪方面排查问题了？基于gazebo的仿真频率大概是20hz
adjust:
  q_s: 0.5 
  p_u: 5. 。
  eta: 10.0 
  d_max: 0.5 
  d_min: 0.1

**Comment by hanruihua** [comment]
有可能是 receding 太短，加速度太大了，可以尝试增加receding，减小 max_acce 和 p_u

**Comment by hanruihua** [comment]
ir-sim 和 Gazebo 的物理模型有些不同，ir-sim只是相对简单的同步的运动学仿真，而 Gazebo 里用的是更接近实际的物理引擎的异步仿真。 这些权重参数在cost function 中是相互作用的，建议调整的时候避免同时调整多个参数，而是固定几个参数 （例如 receding, step time），着重调整权重相关的 （例如q_s, p_u）;  同时 initial path 的变化也会影响权重的选择； 对于S形，主要相关的还是 q_s; 避障部分可以调整 d_max  和 eta.

**Comment by olmman** [comment]
> 您好，我目前在gazebo中进行仿真，同样遇到了该问题。我在ROS noetic环境下测试时，小车模型的运动在没有障碍物的情况下基本能够按照参考路径进行。而目前我在ROS humble环境下，将NeuPAN作为局部规划器嵌入到另一个项目的导航栈中时，小车的运动轨迹就呈现S型，以参考路径为中线左右摆动前进，此时基于Gazebo的仿真频率为10hz左右。我在嵌入前已经根据该项目中的urdf模型重新训练了DUNE的权重，首次发现该问题后，我也对neupan配置文件进行了调整，包括尝试增加receding和q_s、减小 max_acce 和 p_u，但情况并没有改善。这种情况下应该怎样调整？

https://github.com/user-attachments/assets/ffed01c5-806d-4f09-808e-0b2401df5fe9

情况如视频所示，蓝色轨迹是订阅的/neupan_initial_path话题的消息，红色轨迹是订阅的/neupan_plan的消息，当前配置文件设置如下

```
# mpc
receding: 25 #
step_time: 0.3
ref_speed: 2.0 # 原本为0.3
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [1, 1.2]
  max_acce: [0.5, 1.0]
  length: 0.7
  width: 0.4

# initial path
ipath:
  interval: 0.09
  # waypoints: [[0, 0, 0], [5, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: False
  arrive_threshold: 0.8
  close_threshold: 0.1
  arrive_index_threshold: 3
  
# proximal alternating minimization network
pan:
  iter_num: 4
  dune_max_num: 100
  nrmp_max_num: 10
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 4.0  
  p_u: 0.5
  eta: 10.0
  d_max: 0.15
  d_min: 0.01
  ro_obs: 450
```
且这已经是调整参数后相对较好的结果了，但还是呈现S型轨迹

**Comment by hanruihua** [comment]
> > 您好，我目前在gazebo中进行仿真，同样遇到了该问题。我在ROS noetic环境下测试时，小车模型的运动在没有障碍物的情况下基本能够按照参考路径进行。而目前我在ROS humble环境下，将NeuPAN作为局部规划器嵌入到另一个项目的导航栈中时，小车的运动轨迹就呈现S型，以参考路径为中线左右摆动前进，此时基于Gazebo的仿真频率为10hz左右。我在嵌入前已经根据该项目中的urdf模型重新训练了DUNE的权重，首次发现该问题后，我也对neupan配置文件进行了调整，包括尝试增加receding和q_s、减小 max_acce 和 p_u，但情况并没有改善。这种情况下应该怎样调整？
> 
>  VID_20250627_112746.mp4 
> 情况如视频所示，蓝色轨迹是订阅的/neupan_initial_path话题的消息，红色轨迹是订阅的/neupan_plan的消息，当前配置文件设置如下
> 
> ```
> # mpc
> receding: 25 #
> step_time: 0.3
> ref_speed: 2.0 # 原本为0.3
> device: 'cpu'
> time_print: False
> collision_threshold: 0.01
> 
> # robot
> robot:
>   kinematics: 'diff'
>   max_speed: [1, 1.2]
>   max_acce: [0.5, 1.0]
>   length: 0.7
>   width: 0.4
> 
> # initial path
> ipath:
>   interval: 0.09
>   # waypoints: [[0, 0, 0], [5, 0, 0]]
>   curve_style: 'line'   # 'dubins' or reeds or line
>   min_radius: 0.0
>   loop: False
>   arrive_threshold: 0.8
>   close_threshold: 0.1
>   arrive_index_threshold: 3
>   
> # proximal alternating minimization network
> pan:
>   iter_num: 4
>   dune_max_num: 100
>   nrmp_max_num: 10
>   dune_checkpoint: None
>   iter_threshold: 0.1
> 
> # adjust parameters
> adjust:
>   q_s: 4.0  
>   p_u: 0.5
>   eta: 10.0
>   d_max: 0.15
>   d_min: 0.01
>   ro_obs: 450
> ```
> 
> 且这已经是调整参数后相对较好的结果了，但还是呈现S型轨迹

你的 ref_speed 设置的 2，但是 max speed 对应的线速度是1，这就不合理了，理论上ref_speed 应该是小于 max speed， 同时， 建议调小 max_acce 和 step_time， 也可以减小轨迹的波动，频率允许的情况下， step_time 越小控制越灵敏。

**Comment by olmman** [comment]
> > > 您好，我目前在gazebo中进行仿真，同样遇到了该问题。我在ROS noetic环境下测试时，小车模型的运动在没有障碍物的情况下基本能够按照参考路径进行。而目前我在ROS humble环境下，将NeuPAN作为局部规划器嵌入到另一个项目的导航栈中时，小车的运动轨迹就呈现S型，以参考路径为中线左右摆动前进，此时基于Gazebo的仿真频率为10hz左右。我在嵌入前已经根据该项目中的urdf模型重新训练了DUNE的权重，首次发现该问题后，我也对neupan配置文件进行了调整，包括尝试增加receding和q_s、减小 max_acce 和 p_u，但情况并没有改善。这种情况下应该怎样调整？
> > 
> > 
> > VID_20250627_112746.mp4
> > 情况如视频所示，蓝色轨迹是订阅的/neupan_initial_path话题的消息，红色轨迹是订阅的/neupan_plan的消息，当前配置文件设置如下
> > ```
> > # mpc
> > receding: 25 #
> > step_time: 0.3
> > ref_speed: 2.0 # 原本为0.3
> > device: 'cpu'
> > time_print: False
> > collision_threshold: 0.01
> > 
> > # robot
> > robot:
> >   kinematics: 'diff'
> >   max_speed: [1, 1.2]
> >   max_acce: [0.5, 1.0]
> >   length: 0.7
> >   width: 0.4
> > 
> > # initial path
> > ipath:
> >   interval: 0.09
> >   # waypoints: [[0, 0, 0], [5, 0, 0]]
> >   curve_style: 'line'   # 'dubins' or reeds or line
> >   min_radius: 0.0
> >   loop: False
> >   arrive_threshold: 0.8
> >   close_threshold: 0.1
> >   arrive_index_threshold: 3
> >   
> > # proximal alternating minimization network
> > pan:
> >   iter_num: 4
> >   dune_max_num: 100
> >   nrmp_max_num: 10
> >   dune_checkpoint: None
> >   iter_threshold: 0.1
> > 
> > # adjust parameters
> > adjust:
> >   q_s: 4.0  
> >   p_u: 0.5
> >   eta: 10.0
> >   d_max: 0.15
> >   d_min: 0.01
> >   ro_obs: 450
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 且这已经是调整参数后相对较好的结果了，但还是呈现S型轨迹
> 
> 你的 ref_speed 设置的 2，但是 max speed 对应的线速度是1，这就不合理了，理论上ref_speed 应该是小于 max speed， 同时， 建议调小 max_acce 和 step_time， 也可以减小轨迹的波动，频率允许的情况下， step_time 越小控制越灵敏。

感谢您的建议

```
# mpc
receding: 25 
step_time: 0.15
ref_speed: 1.5 
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [1.0, 2.0]
  max_acce: [0.3, 0.5]
  length: 0.7
  width: 0.4
```

目前修改为了上面的参数设置，达到了视频中的效果，改善较大。

https://github.com/user-attachments/assets/077dc808-3f2b-4d69-afd7-045a4e4308d3

但奇怪的是，观察到/neupan_plan与/neupan_initial_path的路径基本吻合，但小车模型在运动中仍然呈现摆头前进的现象，这是为什么？我比较担心在实机部署时也会出现这种情况
