### ISSUE TITLE
轨迹穿过障碍物的问题

### ISSUE THREAD

**Issue by TerryLSR** [hanruihua/neupan_ros#28]
hi，感谢开源如此好的工作
最近在调整机器人外形重新训练后，在仿真环境中避障并无问题。但是在实际机器人上，偶尔会有轨迹穿墙的现象，如图

![Image](https://github.com/user-attachments/assets/9820adc0-1de0-4b1d-9bd6-e479e5d3b8d4)
红色是neupan的轨迹neupan_plan，紫色是dune_point_markers，绿色是neupan_ref_state

这是配置文件
```
# mpc
receding: 10
step_time: 0.2
ref_speed: 0.6
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [0.62, 0.8]
  max_acce: [0.3, 0.6]
  # length: 0.76
  # width: 0.32
  vertices: [[-0.15, -0.28], [-0.15, 0.28], [0.15, 0.28], [0.15, -0.28]]

# initial path
ipath:
  interval: 0.09
  waypoints: [[0, 0, 0], [5, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: False
  arrive_threshold: 0.5
  close_threshold: 0.1
  arrive_index_threshold: 3
  
# proximal alternating minimization network
pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  dune_checkpoint: src/py_pubsub/model/model_5000.pth
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.4
  p_u: 4.0
  eta: 15.0
  d_max: 0.25
  d_min: 0.04
```
是否是因为障碍物的距离约束为绝对值？让前左前右的激光盲区导致优化的轨迹刚好能穿过？
